"""initial schema

Revision ID: 30ed34858f6d
Revises: 
Create Date: 2026-08-18 21:23:15.182036
"""
from alembic import op
import sqlalchemy as sa


revision = '30ed34858f6d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('care_appointment',
    sa.Column('appointment_id', sa.String(length=63), nullable=False),
    sa.Column('tenant_id', sa.String(length=63), nullable=False),
    sa.Column('patient_id', sa.String(length=63), nullable=False),
    sa.Column('starts_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('doctor_name', sa.String(length=255), nullable=False),
    sa.Column('specialty', sa.String(length=64), nullable=True),
    sa.Column('facility', sa.String(length=255), nullable=False),
    sa.Column('purpose', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('reminder_offsets_hours', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('appointment_id')
    )
    op.create_index(op.f('ix_care_appointment_patient_id'), 'care_appointment', ['patient_id'], unique=False)
    op.create_index(op.f('ix_care_appointment_tenant_id'), 'care_appointment', ['tenant_id'], unique=False)
    op.create_index('ix_care_appt_patient', 'care_appointment', ['tenant_id', 'patient_id', 'starts_at'], unique=False)
    op.create_table('care_preparation_step',
    sa.Column('step_id', sa.String(length=63), nullable=False),
    sa.Column('tenant_id', sa.String(length=63), nullable=False),
    sa.Column('patient_id', sa.String(length=63), nullable=False),
    sa.Column('appointment_id', sa.String(length=63), nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('label', sa.String(length=255), nullable=False),
    sa.Column('due_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('source_document', sa.Text(), nullable=True),
    sa.Column('evidence', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['appointment_id'], ['care_appointment.appointment_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('step_id')
    )
    op.create_index('ix_care_prep_appt', 'care_preparation_step', ['tenant_id', 'appointment_id', 'due_at'], unique=False)
    op.create_index(op.f('ix_care_preparation_step_appointment_id'), 'care_preparation_step', ['appointment_id'], unique=False)
    op.create_index(op.f('ix_care_preparation_step_patient_id'), 'care_preparation_step', ['patient_id'], unique=False)
    op.create_index(op.f('ix_care_preparation_step_tenant_id'), 'care_preparation_step', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_care_preparation_step_tenant_id'), table_name='care_preparation_step')
    op.drop_index(op.f('ix_care_preparation_step_patient_id'), table_name='care_preparation_step')
    op.drop_index(op.f('ix_care_preparation_step_appointment_id'), table_name='care_preparation_step')
    op.drop_index('ix_care_prep_appt', table_name='care_preparation_step')
    op.drop_table('care_preparation_step')
    op.drop_index('ix_care_appt_patient', table_name='care_appointment')
    op.drop_index(op.f('ix_care_appointment_tenant_id'), table_name='care_appointment')
    op.drop_index(op.f('ix_care_appointment_patient_id'), table_name='care_appointment')
    op.drop_table('care_appointment')
    # ### end Alembic commands ###
