"""initial schema

Revision ID: 878bdcfa69a1
Revises: 
Create Date: 2026-08-18 21:04:53.063232
"""
from alembic import op
import sqlalchemy as sa


revision = '878bdcfa69a1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ap_audit_event',
    sa.Column('event_id', sa.String(length=63), nullable=False),
    sa.Column('event_type', sa.String(length=64), nullable=False),
    sa.Column('care_event_type', sa.String(length=64), nullable=True),
    sa.Column('tenant_id', sa.String(length=63), nullable=False),
    sa.Column('workspace_id', sa.String(length=63), nullable=True),
    sa.Column('subject_type', sa.String(length=32), nullable=False),
    sa.Column('subject_id', sa.String(length=63), nullable=False),
    sa.Column('job_id', sa.String(length=63), nullable=True),
    sa.Column('execution_id', sa.String(length=63), nullable=True),
    sa.Column('agent_id', sa.String(length=63), nullable=True),
    sa.Column('correlation_id', sa.String(length=63), nullable=True),
    sa.Column('actor', sa.JSON(), nullable=True),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('source_kind', sa.String(length=16), nullable=False),
    sa.Column('source_system', sa.String(length=64), nullable=True),
    sa.Column('transition', sa.JSON(), nullable=True),
    sa.Column('policy_result', sa.JSON(), nullable=True),
    sa.Column('severity', sa.String(length=16), nullable=True),
    sa.Column('evidence', sa.JSON(), nullable=True),
    sa.Column('attributes', sa.JSON(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('event_id')
    )
    op.create_index('ix_ap_audit_correlation', 'ap_audit_event', ['correlation_id'], unique=False)
    op.create_index(op.f('ix_ap_audit_event_care_event_type'), 'ap_audit_event', ['care_event_type'], unique=False)
    op.create_index(op.f('ix_ap_audit_event_event_type'), 'ap_audit_event', ['event_type'], unique=False)
    op.create_index(op.f('ix_ap_audit_event_job_id'), 'ap_audit_event', ['job_id'], unique=False)
    op.create_index(op.f('ix_ap_audit_event_tenant_id'), 'ap_audit_event', ['tenant_id'], unique=False)
    op.create_index('ix_ap_audit_subject', 'ap_audit_event', ['tenant_id', 'subject_type', 'subject_id'], unique=False)
    op.create_index('ix_ap_audit_tenant_time', 'ap_audit_event', ['tenant_id', 'occurred_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_ap_audit_tenant_time', table_name='ap_audit_event')
    op.drop_index('ix_ap_audit_subject', table_name='ap_audit_event')
    op.drop_index(op.f('ix_ap_audit_event_tenant_id'), table_name='ap_audit_event')
    op.drop_index(op.f('ix_ap_audit_event_job_id'), table_name='ap_audit_event')
    op.drop_index(op.f('ix_ap_audit_event_event_type'), table_name='ap_audit_event')
    op.drop_index(op.f('ix_ap_audit_event_care_event_type'), table_name='ap_audit_event')
    op.drop_index('ix_ap_audit_correlation', table_name='ap_audit_event')
    op.drop_table('ap_audit_event')
    # ### end Alembic commands ###
