"""initial schema

Revision ID: 3bed178e8186
Revises: 
Create Date: 2026-08-18 21:04:50.350966
"""
from alembic import op
import sqlalchemy as sa


revision = '3bed178e8186'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ap_tenant',
    sa.Column('tenant_id', sa.String(length=63), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=False),
    sa.Column('timezone', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('tenant_id')
    )
    op.create_table('ap_consent_grant',
    sa.Column('grant_id', sa.String(length=63), nullable=False),
    sa.Column('tenant_id', sa.String(length=63), nullable=False),
    sa.Column('subject_id', sa.String(length=63), nullable=False),
    sa.Column('grantee_type', sa.String(length=16), nullable=False),
    sa.Column('grantee_id', sa.String(length=63), nullable=False),
    sa.Column('scopes', sa.JSON(), nullable=False),
    sa.Column('purpose', sa.String(length=32), nullable=False),
    sa.Column('granted_by_type', sa.String(length=16), nullable=False),
    sa.Column('granted_by_id', sa.String(length=63), nullable=False),
    sa.Column('granted_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['ap_tenant.tenant_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('grant_id')
    )
    op.create_index(op.f('ix_ap_consent_grant_grantee_id'), 'ap_consent_grant', ['grantee_id'], unique=False)
    op.create_index(op.f('ix_ap_consent_grant_subject_id'), 'ap_consent_grant', ['subject_id'], unique=False)
    op.create_index(op.f('ix_ap_consent_grant_tenant_id'), 'ap_consent_grant', ['tenant_id'], unique=False)
    op.create_index('ix_ap_consent_lookup', 'ap_consent_grant', ['tenant_id', 'subject_id', 'grantee_id'], unique=False)
    op.create_table('ap_tenant_member',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.String(length=63), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['ap_tenant.tenant_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'user_id', name='uq_ap_member')
    )
    op.create_index(op.f('ix_ap_tenant_member_tenant_id'), 'ap_tenant_member', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_ap_tenant_member_user_id'), 'ap_tenant_member', ['user_id'], unique=False)
    op.create_table('ap_workspace',
    sa.Column('workspace_id', sa.String(length=63), nullable=False),
    sa.Column('tenant_id', sa.String(length=63), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['ap_tenant.tenant_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('workspace_id')
    )
    op.create_index(op.f('ix_ap_workspace_tenant_id'), 'ap_workspace', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ap_workspace_tenant_id'), table_name='ap_workspace')
    op.drop_table('ap_workspace')
    op.drop_index(op.f('ix_ap_tenant_member_user_id'), table_name='ap_tenant_member')
    op.drop_index(op.f('ix_ap_tenant_member_tenant_id'), table_name='ap_tenant_member')
    op.drop_table('ap_tenant_member')
    op.drop_index('ix_ap_consent_lookup', table_name='ap_consent_grant')
    op.drop_index(op.f('ix_ap_consent_grant_tenant_id'), table_name='ap_consent_grant')
    op.drop_index(op.f('ix_ap_consent_grant_subject_id'), table_name='ap_consent_grant')
    op.drop_index(op.f('ix_ap_consent_grant_grantee_id'), table_name='ap_consent_grant')
    op.drop_table('ap_consent_grant')
    op.drop_table('ap_tenant')
    # ### end Alembic commands ###
