"""consent v1 alignment

Revision ID: 6a77dc4afa13
Revises: 3bed178e8186
Create Date: 2026-08-19 01:21:45.404101
"""
from alembic import op
import sqlalchemy as sa


revision = '6a77dc4afa13'
down_revision = '3bed178e8186'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ap_consent_grant', sa.Column('authority_basis', sa.String(length=255), nullable=True))
    op.add_column('ap_consent_grant', sa.Column('workspace_id', sa.String(length=63), nullable=True))
    op.add_column('ap_consent_grant', sa.Column('revoked_by_type', sa.String(length=16), nullable=True))
    op.add_column('ap_consent_grant', sa.Column('revoked_by_id', sa.String(length=63), nullable=True))
    op.add_column('ap_consent_grant', sa.Column('revoked_reason', sa.String(length=255), nullable=True))
    op.drop_column('ap_consent_grant', 'active')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ap_consent_grant', sa.Column('active', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_column('ap_consent_grant', 'revoked_reason')
    op.drop_column('ap_consent_grant', 'revoked_by_id')
    op.drop_column('ap_consent_grant', 'revoked_by_type')
    op.drop_column('ap_consent_grant', 'workspace_id')
    op.drop_column('ap_consent_grant', 'authority_basis')
    # ### end Alembic commands ###
