"""initial schema

Revision ID: 96a5a96b099c
Revises: 
Create Date: 2026-08-18 21:05:00.612393
"""
from alembic import op
import sqlalchemy as sa


revision = '96a5a96b099c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('care_routine_item',
    sa.Column('routine_id', sa.String(length=63), nullable=False),
    sa.Column('tenant_id', sa.String(length=63), nullable=False),
    sa.Column('patient_id', sa.String(length=63), nullable=False),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('label', sa.String(length=255), nullable=False),
    sa.Column('scheduled_time', sa.String(length=5), nullable=False),
    sa.Column('recurrence_type', sa.String(length=16), nullable=False),
    sa.Column('days_of_week', sa.JSON(), nullable=True),
    sa.Column('grace_minutes', sa.Integer(), nullable=False),
    sa.Column('severity', sa.String(length=16), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('routine_id')
    )
    op.create_index(op.f('ix_care_routine_item_patient_id'), 'care_routine_item', ['patient_id'], unique=False)
    op.create_index(op.f('ix_care_routine_item_tenant_id'), 'care_routine_item', ['tenant_id'], unique=False)
    op.create_index('ix_care_routine_patient', 'care_routine_item', ['tenant_id', 'patient_id', 'enabled'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_care_routine_patient', table_name='care_routine_item')
    op.drop_index(op.f('ix_care_routine_item_tenant_id'), table_name='care_routine_item')
    op.drop_index(op.f('ix_care_routine_item_patient_id'), table_name='care_routine_item')
    op.drop_table('care_routine_item')
    # ### end Alembic commands ###
