"""initial schema

Revision ID: 79ae332e80c5
Revises: 
Create Date: 2026-08-18 21:04:58.152784
"""
from alembic import op
import sqlalchemy as sa


revision = '79ae332e80c5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('care_job',
    sa.Column('care_job_id', sa.String(length=63), nullable=False),
    sa.Column('tenant_id', sa.String(length=63), nullable=False),
    sa.Column('patient_id', sa.String(length=63), nullable=False),
    sa.Column('source_kind', sa.String(length=24), nullable=False),
    sa.Column('source_id', sa.String(length=63), nullable=False),
    sa.Column('label', sa.String(length=255), nullable=False),
    sa.Column('state', sa.String(length=16), nullable=False),
    sa.Column('severity', sa.String(length=16), nullable=False),
    sa.Column('due_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('max_attempts', sa.Integer(), nullable=False),
    sa.Column('next_attempt_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('correlation_id', sa.String(length=63), nullable=False),
    sa.Column('evidence', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('care_job_id')
    )
    op.create_index(op.f('ix_care_job_correlation_id'), 'care_job', ['correlation_id'], unique=False)
    op.create_index('ix_care_job_due', 'care_job', ['tenant_id', 'state', 'next_attempt_at'], unique=False)
    op.create_index('ix_care_job_patient', 'care_job', ['tenant_id', 'patient_id', 'due_at'], unique=False)
    op.create_index(op.f('ix_care_job_patient_id'), 'care_job', ['patient_id'], unique=False)
    op.create_index('ix_care_job_source', 'care_job', ['tenant_id', 'source_kind', 'source_id', 'due_at'], unique=False)
    op.create_index(op.f('ix_care_job_tenant_id'), 'care_job', ['tenant_id'], unique=False)
    op.create_table('care_notification',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.String(length=63), nullable=False),
    sa.Column('patient_id', sa.String(length=63), nullable=False),
    sa.Column('audience', sa.String(length=16), nullable=False),
    sa.Column('target_principal_id', sa.String(length=63), nullable=False),
    sa.Column('channel', sa.String(length=16), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('severity', sa.String(length=16), nullable=False),
    sa.Column('care_job_id', sa.String(length=63), nullable=True),
    sa.Column('correlation_id', sa.String(length=63), nullable=True),
    sa.Column('aggregated_count', sa.Integer(), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_care_notif_lookup', 'care_notification', ['tenant_id', 'patient_id', 'audience', 'sent_at'], unique=False)
    op.create_index(op.f('ix_care_notification_care_job_id'), 'care_notification', ['care_job_id'], unique=False)
    op.create_index(op.f('ix_care_notification_patient_id'), 'care_notification', ['patient_id'], unique=False)
    op.create_index(op.f('ix_care_notification_tenant_id'), 'care_notification', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_care_notification_tenant_id'), table_name='care_notification')
    op.drop_index(op.f('ix_care_notification_patient_id'), table_name='care_notification')
    op.drop_index(op.f('ix_care_notification_care_job_id'), table_name='care_notification')
    op.drop_index('ix_care_notif_lookup', table_name='care_notification')
    op.drop_table('care_notification')
    op.drop_index(op.f('ix_care_job_tenant_id'), table_name='care_job')
    op.drop_index('ix_care_job_source', table_name='care_job')
    op.drop_index(op.f('ix_care_job_patient_id'), table_name='care_job')
    op.drop_index('ix_care_job_patient', table_name='care_job')
    op.drop_index('ix_care_job_due', table_name='care_job')
    op.drop_index(op.f('ix_care_job_correlation_id'), table_name='care_job')
    op.drop_table('care_job')
    # ### end Alembic commands ###
