"""add notification delivery status

Revision ID: dbcd7519fc5e
Revises: 79ae332e80c5
Create Date: 2026-08-18 21:39:21.251476
"""
from alembic import op
import sqlalchemy as sa


revision = 'dbcd7519fc5e'
down_revision = '79ae332e80c5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('care_notification', sa.Column('delivery_status', sa.String(length=16), nullable=False))
    op.add_column('care_notification', sa.Column('delivery_error', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('care_notification', 'delivery_error')
    op.drop_column('care_notification', 'delivery_status')
    # ### end Alembic commands ###
