"""initial schema

Revision ID: 412f2a69227b
Revises: 
Create Date: 2026-08-18 21:05:04.286159
"""
from alembic import op
import sqlalchemy as sa


revision = '412f2a69227b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('care_medication_version',
    sa.Column('version_id', sa.String(length=63), nullable=False),
    sa.Column('medication_id', sa.String(length=63), nullable=False),
    sa.Column('tenant_id', sa.String(length=63), nullable=False),
    sa.Column('patient_id', sa.String(length=63), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('normalized_name', sa.String(length=255), nullable=False),
    sa.Column('route', sa.String(length=32), nullable=False),
    sa.Column('schedule', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('instruction_source', sa.String(length=32), nullable=False),
    sa.Column('prescribed_by', sa.JSON(), nullable=True),
    sa.Column('effective_from', sa.DateTime(timezone=True), nullable=False),
    sa.Column('superseded_by', sa.String(length=63), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('confirmed_by', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('version_id')
    )
    op.create_index('ix_care_med_active', 'care_medication_version', ['tenant_id', 'patient_id', 'status'], unique=False)
    op.create_index('ix_care_med_chain', 'care_medication_version', ['tenant_id', 'medication_id', 'effective_from'], unique=False)
    op.create_index(op.f('ix_care_medication_version_medication_id'), 'care_medication_version', ['medication_id'], unique=False)
    op.create_index(op.f('ix_care_medication_version_normalized_name'), 'care_medication_version', ['normalized_name'], unique=False)
    op.create_index(op.f('ix_care_medication_version_patient_id'), 'care_medication_version', ['patient_id'], unique=False)
    op.create_index(op.f('ix_care_medication_version_tenant_id'), 'care_medication_version', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_care_medication_version_tenant_id'), table_name='care_medication_version')
    op.drop_index(op.f('ix_care_medication_version_patient_id'), table_name='care_medication_version')
    op.drop_index(op.f('ix_care_medication_version_normalized_name'), table_name='care_medication_version')
    op.drop_index(op.f('ix_care_medication_version_medication_id'), table_name='care_medication_version')
    op.drop_index('ix_care_med_chain', table_name='care_medication_version')
    op.drop_index('ix_care_med_active', table_name='care_medication_version')
    op.drop_table('care_medication_version')
    # ### end Alembic commands ###
