"""initial schema

Revision ID: 713a7af12c06
Revises: 
Create Date: 2026-08-18 21:05:07.703698
"""
from alembic import op
import sqlalchemy as sa


revision = '713a7af12c06'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('care_journal_entry',
    sa.Column('entry_id', sa.String(length=63), nullable=False),
    sa.Column('tenant_id', sa.String(length=63), nullable=False),
    sa.Column('patient_id', sa.String(length=63), nullable=False),
    sa.Column('entry_type', sa.String(length=16), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('recorded_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('recorded_by', sa.JSON(), nullable=False),
    sa.Column('classification', sa.String(length=24), nullable=False),
    sa.Column('target_specialty', sa.String(length=64), nullable=True),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('answer', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('entry_id')
    )
    op.create_index(op.f('ix_care_journal_entry_patient_id'), 'care_journal_entry', ['patient_id'], unique=False)
    op.create_index(op.f('ix_care_journal_entry_tenant_id'), 'care_journal_entry', ['tenant_id'], unique=False)
    op.create_index('ix_care_journal_patient', 'care_journal_entry', ['tenant_id', 'patient_id', 'status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_care_journal_patient', table_name='care_journal_entry')
    op.drop_index(op.f('ix_care_journal_entry_tenant_id'), table_name='care_journal_entry')
    op.drop_index(op.f('ix_care_journal_entry_patient_id'), table_name='care_journal_entry')
    op.drop_table('care_journal_entry')
    # ### end Alembic commands ###
