"""initial schema

Revision ID: 2790547d289f
Revises: 
Create Date: 2026-08-18 21:39:24.185465
"""
from alembic import op
import sqlalchemy as sa


revision = '2790547d289f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('care_line_binding',
    sa.Column('binding_id', sa.String(length=63), nullable=False),
    sa.Column('tenant_id', sa.String(length=63), nullable=False),
    sa.Column('channel_id', sa.String(length=64), nullable=False),
    sa.Column('line_user_id', sa.String(length=64), nullable=False),
    sa.Column('principal_id', sa.String(length=63), nullable=False),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.Column('patient_id', sa.String(length=63), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('binding_id'),
    sa.UniqueConstraint('channel_id', 'line_user_id', name='uq_care_line_binding')
    )
    op.create_index(op.f('ix_care_line_binding_channel_id'), 'care_line_binding', ['channel_id'], unique=False)
    op.create_index(op.f('ix_care_line_binding_line_user_id'), 'care_line_binding', ['line_user_id'], unique=False)
    op.create_index(op.f('ix_care_line_binding_patient_id'), 'care_line_binding', ['patient_id'], unique=False)
    op.create_index(op.f('ix_care_line_binding_principal_id'), 'care_line_binding', ['principal_id'], unique=False)
    op.create_index(op.f('ix_care_line_binding_tenant_id'), 'care_line_binding', ['tenant_id'], unique=False)
    op.create_index('ix_care_line_principal', 'care_line_binding', ['tenant_id', 'principal_id'], unique=False)
    op.create_table('care_line_pairing_code',
    sa.Column('code', sa.String(length=16), nullable=False),
    sa.Column('tenant_id', sa.String(length=63), nullable=False),
    sa.Column('patient_id', sa.String(length=63), nullable=False),
    sa.Column('principal_id', sa.String(length=63), nullable=False),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=False),
    sa.Column('created_by', sa.String(length=63), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('code')
    )
    op.create_index(op.f('ix_care_line_pairing_code_patient_id'), 'care_line_pairing_code', ['patient_id'], unique=False)
    op.create_index(op.f('ix_care_line_pairing_code_tenant_id'), 'care_line_pairing_code', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_care_line_pairing_code_tenant_id'), table_name='care_line_pairing_code')
    op.drop_index(op.f('ix_care_line_pairing_code_patient_id'), table_name='care_line_pairing_code')
    op.drop_table('care_line_pairing_code')
    op.drop_index('ix_care_line_principal', table_name='care_line_binding')
    op.drop_index(op.f('ix_care_line_binding_tenant_id'), table_name='care_line_binding')
    op.drop_index(op.f('ix_care_line_binding_principal_id'), table_name='care_line_binding')
    op.drop_index(op.f('ix_care_line_binding_patient_id'), table_name='care_line_binding')
    op.drop_index(op.f('ix_care_line_binding_line_user_id'), table_name='care_line_binding')
    op.drop_index(op.f('ix_care_line_binding_channel_id'), table_name='care_line_binding')
    op.drop_table('care_line_binding')
    # ### end Alembic commands ###
