"""add home_label for orientation

Revision ID: 1c01e2d79662
Revises: f786a31ac09b
Create Date: 2026-08-18 21:20:32.706090
"""
from alembic import op
import sqlalchemy as sa


revision = '1c01e2d79662'
down_revision = 'f786a31ac09b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('care_patient', sa.Column('home_label', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('care_patient', 'home_label')
    # ### end Alembic commands ###
