"""initial schema

Revision ID: f786a31ac09b
Revises: 
Create Date: 2026-08-18 21:04:55.629581
"""
from alembic import op
import sqlalchemy as sa


revision = 'f786a31ac09b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('care_caregiver',
    sa.Column('caregiver_id', sa.String(length=63), nullable=False),
    sa.Column('tenant_id', sa.String(length=63), nullable=False),
    sa.Column('principal_id', sa.String(length=63), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=False),
    sa.Column('relation', sa.String(length=64), nullable=False),
    sa.Column('channel', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('caregiver_id')
    )
    op.create_index(op.f('ix_care_caregiver_principal_id'), 'care_caregiver', ['principal_id'], unique=False)
    op.create_index(op.f('ix_care_caregiver_tenant_id'), 'care_caregiver', ['tenant_id'], unique=False)
    op.create_table('care_patient',
    sa.Column('patient_id', sa.String(length=63), nullable=False),
    sa.Column('tenant_id', sa.String(length=63), nullable=False),
    sa.Column('workspace_id', sa.String(length=63), nullable=True),
    sa.Column('display_name', sa.String(length=255), nullable=False),
    sa.Column('timezone', sa.String(length=64), nullable=False),
    sa.Column('care_profile', sa.JSON(), nullable=False),
    sa.Column('channels', sa.JSON(), nullable=False),
    sa.Column('quiet_hours_start', sa.String(length=5), nullable=True),
    sa.Column('quiet_hours_end', sa.String(length=5), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('patient_id')
    )
    op.create_index('ix_care_patient_tenant', 'care_patient', ['tenant_id', 'status'], unique=False)
    op.create_index(op.f('ix_care_patient_tenant_id'), 'care_patient', ['tenant_id'], unique=False)
    op.create_table('care_team_member',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.String(length=63), nullable=False),
    sa.Column('patient_id', sa.String(length=63), nullable=False),
    sa.Column('caregiver_id', sa.String(length=63), nullable=False),
    sa.Column('escalation_order', sa.Integer(), nullable=False),
    sa.Column('is_emergency_contact', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['caregiver_id'], ['care_caregiver.caregiver_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['patient_id'], ['care_patient.patient_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_care_team_member_patient_id'), 'care_team_member', ['patient_id'], unique=False)
    op.create_index(op.f('ix_care_team_member_tenant_id'), 'care_team_member', ['tenant_id'], unique=False)
    op.create_index('ix_care_team_patient', 'care_team_member', ['tenant_id', 'patient_id', 'escalation_order'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_care_team_patient', table_name='care_team_member')
    op.drop_index(op.f('ix_care_team_member_tenant_id'), table_name='care_team_member')
    op.drop_index(op.f('ix_care_team_member_patient_id'), table_name='care_team_member')
    op.drop_table('care_team_member')
    op.drop_index(op.f('ix_care_patient_tenant_id'), table_name='care_patient')
    op.drop_index('ix_care_patient_tenant', table_name='care_patient')
    op.drop_table('care_patient')
    op.drop_index(op.f('ix_care_caregiver_tenant_id'), table_name='care_caregiver')
    op.drop_index(op.f('ix_care_caregiver_principal_id'), table_name='care_caregiver')
    op.drop_table('care_caregiver')
    # ### end Alembic commands ###
